name: Deploy Docusaurus Preview
on:
  pull_request:
    paths:
      - 'docusaurus-site/**/*'
      - '.github/workflows/preview-docusaurus.yml'
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: docusaurus-site/package-lock.json

      - name: Install dependencies
        working-directory: docusaurus-site
        run: npm ci

      - name: Build website
        id: build
        working-directory: docusaurus-site
        run: npm run build

      - name: Deploy preview
        if: success() && steps.build.outcome == 'success'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docusaurus-site/build
          destination_dir: ${{ github.event_name == 'pull_request' && format('preview/pr-{0}', github.event.pull_request.number) || format('preview/run-{0}', github.run_id) }}
